#                          Generated on docker.io                          #
version: "3.1"
services:
    mysql:
        image: mysql:8.0
        container_name: cloudbeds-mysql
        volumes:
            - ./mysql-storage:/var/lib/mysql
            - ./mysql-init:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=cloudbeds
            - MYSQL_PASSWORD=root
        ports:
            - "33306:3306"

    webserver:
        build: docker/nginx
        container_name: cloudbeds-webserver
        working_dir: /app
        ports:
            - "8080:80"

    php-fpm:
        build: docker/php-fpm
        container_name: cloudbeds-php-fpm
        working_dir: /app
        volumes:
            - .:/app
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
        environment:
            XDEBUG_CONFIG: "remote_host=${DOCKER_HOST_IP}"
            PHP_IDE_CONFIG: "serverName=Cloudbeds"